<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CheapAI.BackgroundJobs-7cfe9336-1e03-44ba-a913-f9731d53db56</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Hangfire.MySqlStorage" Version="2.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CheapAI.Application\CheapAI.Application.csproj" />
    <ProjectReference Include="..\CheapAI.Infrastructure\CheapAI.Infrastructure.csproj" />
  </ItemGroup>
</Project>
